const ansi = require('ansi')
const cursor = ansi(process.stdout)
 
cursor
    .reset()
    .write('   ')
    .bold()
    .fg.red()
    .write('Shirish Sigdyal \n')
    .fg.reset()
    .fg.cyan()
    .write('   Shirish Sigdyal \n')
    .fg.reset()
    .fg.magenta()
    .write('   Shirish Sigdyal \n')
    .fg.reset()
    .fg.brightYellow()
    .write('   Shirish Sigdyal \n')
    .fg.reset()
    .reset()